language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

addons:
  code_climate:
    repo_token: 9142fd9b94ff6cef1ed0847647451df0b621012d580dc3c35c9f070093d0aea4

install:
  - composer install

script:
  - phpunit --verbose $PHPUNIT_FLAGS

after_success:
  - vendor/bin/test-reporter